version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: ${DB_NAME:-study_planner} # Replace with your DB name if needed
      POSTGRES_USER: ${DB_USER:-postgres}  # Your DB username
      POSTGRES_PASSWORD: ${DB_PASSWORD:-sql03} # Your DB password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d ${DB_NAME:-study_planner}"]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    build: .
    command: python backend/manage.py runserver 0.0.0.0:8000  # Running Django instead of your custom command
    volumes:
      - .:/app
    ports:
      - "8000:8000"  # Django default port
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DEBUG=True
      - DB_NAME=${DB_NAME:-study_planner}  # Django settings
      - DB_USER=${DB_USER:-postgres}
      - DB_PASSWORD=${DB_PASSWORD:-sql03}
      - DB_HOST=db
      - DB_PORT=5432

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL:-22bcaf03@kristujayanti.com} # Replace with your email
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD:-22bcaf03} # Replace with your password
    ports:
      - "5050:80"  # Expose pgAdmin on localhost:5050
    depends_on:
      - db

volumes:
  postgres_data:
