# Generated by Django 5.0.6 on 2025-04-21 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customuser_available_study_hours_studyplan'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studyplan',
            old_name='plan_data',
            new_name='generated_plan',
        ),
        migrations.RemoveField(
            model_name='studyplan',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='studyplan',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='studyplan',
            name='is_single_day',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studyplan',
            name='preferred_time',
            field=models.CharField(default='Morning', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studyplan',
            name='study_goal',
            field=models.TextField(default='Morning'),
            preserve_default=False,
        ),
    ]
