# Generated by Django 5.0.6 on 2025-04-21 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_rename_plan_data_studyplan_generated_plan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='available_study_hours',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
