# Generated by Django 5.0.6 on 2025-04-21 19:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_customuser_available_study_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='studyplan',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
