# Generated by Django 5.0.6 on 2025-04-21 21:32

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_customuser_options_alter_studyplan_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={},
        ),
        migrations.AlterModelOptions(
            name='studyplan',
            options={},
        ),
        migrations.RemoveField(
            model_name='studyplan',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='studyplan',
            name='is_single_day',
        ),
        migrations.RemoveField(
            model_name='studyplan',
            name='preferred_time',
        ),
        migrations.AddField(
            model_name='studyplan',
            name='preferred_study_time',
            field=models.CharField(default='Morning', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customuser',
            name='available_study_hours',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studyplan',
            name='available_study_hours',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='studyplan',
            name='end_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='studyplan',
            name='start_date',
            field=models.DateField(default='2025-04-22'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='studyplan',
            name='study_goal',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='studyplan',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
